# Generated by Django 3.2.13 on 2022-05-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
