# Generated by Django 3.2.13 on 2022-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Poster',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='Title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='Year',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
