# Generated by Django 4.0.5 on 2022-07-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_comments', to='movie.movie'),
        ),
    ]
