# Generated by Django 4.0.5 on 2022-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_usermovierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Fine'), (4, 'Good'), (5, 'Amazing')], null=True),
        ),
        migrations.DeleteModel(
            name='UserMovieRating',
        ),
    ]
