# Generated by Django 4.0.5 on 2022-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_remove_movie_rate_usermovierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierating',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermovierating',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1- Bad'), (2, '2- Ok'), (3, '3- Fine'), (4, '4- Good'), (5, '5- Amazing')]),
        ),
    ]
