# Generated by Django 4.0.5 on 2022-07-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_ratingstar_remove_usermovierating_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.RemoveField(
            model_name='usermovierating',
            name='favorite',
        ),
    ]
