# Generated by Django 4.0.5 on 2022-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_remove_usermovierating_ip_usermovierating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovierating',
            name='user',
        ),
        migrations.AddField(
            model_name='usermovierating',
            name='ip',
            field=models.CharField(max_length=15, null=True, verbose_name='IP адрес'),
        ),
    ]
