# Generated by Django 3.2.14 on 2022-07-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_favoritemovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
